#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
mkdir /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /var/nginx/sites-available/default
service nginx start
